# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21
loader_version=0.15.11
loom_version=1.6.12
yarn_mappings=1.21+build.9

# Mod Properties
mod_id=examplemod
mod_version=1.0.0
maven_group=com.example

# Dependencies
fabric_api_version=0.100.4+1.21
